config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :cars, only: [:index, :show]

  resources :additional_drivers, only: [:new, :edit, :update, :create, :destroy]

  resources :addresses, only: [:new, :edit, :update, :create, :destroy]

  resources :slots, only: [:new, :edit, :update, :create, :destroy]
  post 'dashboard/slot', to: 'slots_json#create', as: :dashboard_slot_json

  #Estimation et souscription

  get "/cars/:id/estimation", to: "cars#estimation", as: "estimation"
  get "/cars/:id/souscription", to: "cars#souscription", as: "souscription"

  #Dashboard routes
  get "/dashboard", to: "dashboards#show", as: :dashboard
  get "/dashboard/bill", to: "dashboards#bill", as: :dashboard_bill
  get "/dashboard/slot", to: "dashboards#slot", as: :dashboard_slot
  get "/profil", to: "dashboards#profile", as: :dashboard_profile

  #Profil routes
  get "/profil/edit", to: "driver_profiles#edit"
  patch "/profil", to: "driver_profiles#update"
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dn3sbzgqs/image/upload/v1520606181/banner.jpg');">

  <div class="btn--discover">
    <p class="tagline-first-line">Mon budget Auto simplifié et optimisé</p>
    <!-- <p class="tagline-second-line">à budget contrôlé</p> -->

    <%= link_to "Découvrir les véhicules Smap",  cars_path, class: "btn-smap" %>
  </div>
</div>

app/views/shared/_card.html.erb
<% url = (cl_image_path car.photo) %>
<div class="card text-center">
  <%= link_to car_path(car), class: "card-body", style:"background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('#{url}')" do %>
  <div class="card-category">
    <h3><%= car.brand %> <%= car.model %></h3>
  </div>
  <div class="card-desc">
   <%= car.monthly_price %> € / mois
  </div>
  <% end %>
    <div class="card-footer">
        <p><%= car.category %> </p>
      <div class="card-icon-list">
        <div class="card-list">
          <h4 class="material-icons-li"><i class="fas fa-users"></i> &nbsp; <%= car.seat %> Places</h4>
          <h4 class="material-icons-li"><i class="tiny material-icons" style="font-size: 20px" >local_gas_station</i> &nbsp; <%= car.energy %></h4>
        </div>
        <div class="card-list">
          <h4 class="material-icons-li"><i class="fas fa-cogs"></i> &nbsp; <%= car.transmission %></h4>
          <h4 class="material-icons-li"><i class="fas fa-car"></i> &nbsp; <%= car.car_door %> Portes</h4>
        </div>
        <div class="card-list">
          <h4 class="material-icons-li"><i class="fas fa-suitcase"></i></i> &nbsp; <%= car.lugage %> Bagages</h4>
        </div>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/smap_mobility/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/smapmobility/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/Smap_mobility"><i class="fab fa-twitter"></i></a>
  </div>

  <div class="footer-copyright">Made at Le Wagon Lyon</div>
</div>

app/views/shared/_homecard.html.erb
<div class="container">
  <div class="homecards">
    <div class="row">
      <div class="col-xs-3 col-sm-3">
        <div class="homecard">
          <div class="img-container"><%= image_tag '1.png' %></div>
          <p>Je choisis le modèle de mon véhicule à tarif mensuel pour 24 mois</p>
        </div>
      </div>

      <div class="col-xs-3 col-sm-3">
        <div class="homecard">
          <div class="img-container"><%= image_tag '2.png' %></div>
          <p>Je renseigne les disponibilités de mon véhicule pour le sous louer</p>
        </div>
      </div>

      <div class="col-xs-3 col-sm-3">
        <div class="homecard">
          <div class="img-container"><%= image_tag '3.png' %></div>
          <p>Grâce au boîtier installé sur le véhicule, pas besoin de rencontrer le sous locataire: il pourra ouvrir les portes grâce à son smartphone</p>
        </div>
      </div>

      <div class="col-xs-3 col-sm-3">
        <div class="homecard">
          <div class="img-container"><%= image_tag '4.png' %></div>
          <p>Mon budget automobile est réduit et simplifié</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_new_slot.html.erb
<div class="modal fade" id="modalNewSlot" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id=""></h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_sign_in.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="myModalLabel">Connectez-vous pour continuer</h1>
      </div>
      <div class="modal-body">
        <div class="containe">
          <div class="row">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1">
              <% user = User.new %>
              <% resource_name = :user %>
              <%= simple_form_for(user, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="form-inputs">
                  <%= f.input :email, label: 'Email', required: false, autofocus: true, placeholder: "bob@gmail.com" %>
                  <%= f.input :password, label:'Mot de passe', required: false, placeholder: "••••••" %>
                  <%= f.input :remember_me, label:'Se souvenir de moi', as: :boolean if Devise.mappings[resource_name].rememberable? %>
                </div>
                <div class="form-actions">

                  <%- if controller_name != 'sessions' %>
                    <%= button_to "Connexion", new_session_path(:user), class: "btn-smap" %><br />
                  <% end -%>

                  <%- if Devise.mappings[:user].recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
                    <%= link_to "Mot de passe oublié?", new_password_path(:user) %><br />
                  <% end -%>
                  <div class="titre">
                    <span class="titre1">
                      <q> ou continuez avec </q>
                    </span>
                  </div>
                  <%- if Devise.mappings[:user].omniauthable? %>
                    <%- User.omniauth_providers.each do |provider| %>
                      <%= button_to "#{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(:user, provider), class: "btn btn-primary" %><br />
                    <% end -%>
                  <% end -%>
                </div>
              <% end -%>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="flex-modal">
          <p>Vous n'avez pas de compte? </p>
          <p>
            <%- if Devise.mappings[:user].registerable? && controller_name != 'registrations' %>
              <%= link_to "Inscription", new_registration_path(:user), class: "btn-smap-secondary" %><br />
            <% end -%>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-smap">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-smap-brand" do %>
    <%= image_tag "logoblanc.png", height: 50 %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-smap-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to " Nos véhicules ",  cars_path , class: "navbar-smap-item navbar-smap-link" %>&nbsp;
      <!-- Avatar with dropdown menu -->
      <div class="navbar-smap-item">
        <div class="dropdown">
              <% if current_user && current_user.driver_profile.photo != nil  %>
            <%= image_tag current_user.driver_profile.photo.url, class:"avatar dropdown-toggle", id:"navbar-smap-menu", data: { toggle: 'dropdown' } %>
            <% elsif %>
            <%= image_tag ("profil.png"), class:"avatar dropdown-toggle", id:"navbar-smap-menu", data: { toggle: 'dropdown' } %>
            <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-smap-dropdown-menu">
            <li><%= link_to "Profil", profil_path %></a></li>
            <li><%= link_to "Tableau de bord", dashboard_path %></a></li>
            <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></a></li>
          </ul>
        </div>
      </div>
    <% else %>


      <!-- Login link (when logged out) -->
      <a class="navbar-smap-item navbar-smap-link " data-toggle="modal" data-target="#myModal">
        Connexion
      </a>
      <%= link_to "Nos véhicules", cars_path, class: "navbar-smap-item navbar-smap-link" %>
      <%= render 'shared/modal_sign_in' %>
    <% end %>
  </div>
</div>