config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :cars, only: [:index, :show]

  resources :additional_drivers, only: [:new, :edit, :update, :create, :destroy]

  resources :addresses, only: [:new, :edit, :update, :create, :destroy]

  resources :slots, only: [:new, :edit, :update, :create, :destroy]
  post 'dashboard/slot', to: 'slots_json#create', as: :dashboard_slot_json

  #Estimation et souscription

  get "/cars/:id/estimation", to: "cars#estimation", as: "estimation"
  get "/cars/:id/souscription", to: "cars#souscription", as: "souscription"

  #Dashboard routes
  get "/dashboard", to: "dashboards#show", as: :dashboard
  get "/dashboard/bill", to: "dashboards#bill", as: :dashboard_bill
  get "/dashboard/slot", to: "dashboards#slot", as: :dashboard_slot
  get "/profil", to: "dashboards#profile", as: :dashboard_profile

  #Profil routes
  get "/profil/edit", to: "driver_profiles#edit"
  patch "/profil", to: "driver_profiles#update"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :set_user

  def show
    @car = @driver_profile.car
  end

  def bill
  end

  def slot
  end

  def profile
    @driver_profile = DriverProfile.find_by user: current_user
    @car = @driver_profile.car
  end

  private

  def set_user
    @driver_profile = DriverProfile.find_by user: current_user
  end
end

app/views/dashboards/_subnav.html.erb
<div class="tabs">
  <a class="tab <%= 'active' if params[:action] == 'profile' %>" href="<%= dashboard_profile_path %>">
    <div>
      <i class="fas fa-address-card"></i><h3>Profil</h3>
    </div>
  </a>
  <a class="tab <%= 'active' if params[:action] == 'show' %>" href="<%= dashboard_path %>">
    <div>
      <i class="fas fa-car"></i><h3>Conducteurs secondaires</h3>
    </div>
  </a>
  <a class="tab <%= 'active' if params[:action] == 'slot' %>" href="<%= dashboard_slot_path %>">
    <div>
      <i class="far fa-calendar-alt"></i><h3>Disponibilités & Adresses</h3>
    </div>
  </a>
  <a class="tab <%= 'active' if params[:action] == 'bill' %>" href="<%= dashboard_bill_path %>">
    <div>
      <i class="far fa-money-bill-alt"></i><h3>Facture</h3>
    </div>
  </a>
</div>

app/views/dashboards/bill.html.erb
<div class="body-wrap">
  <div class="container">
    <%= render 'subnav' %>

    <div class="dash">
    <p> Prix de mon contrat de location Longue Durée Smap: <span id="monthly-price"><%= @driver_profile.car.monthly_price %>€ par mois</span></p>
    <p> Durée : 3 Février 2018 - 2 février 2020 </p>
      <table>
  <caption> Mes Locations Courte Durée </caption>
  <caption> <    Mars 2018     > </caption>
   <tr>
       <th> Date </th>
       <th> Durée </th>
       <th> Locataire Courte Durée </th>
       <th> Economie réalisée </th>
   </tr>

   <tr>
       <td> 03/03/2018 </td>
       <td> 2 jours</td>
       <td> <%= image_tag 'https://clowntownforkidz.files.wordpress.com/2014/01/clown-charlie-chaplin1.jpg', width: 35, height: 35, class: "avatar-courte" %> Jean Jacques Michu</td>
       <td> - 40 € </td>
   </tr>

   <tr>
       <td> 07/03/2018 </td>
       <td> 2 heures </td>
       <td> <%= image_tag 'https://javalosdotme.files.wordpress.com/2012/12/ada_lovelace.jpg?w=570', width: 35, height: 35, class: "avatar-courte" %> Marie Vinot </td>
       <td> - 4 € </td>
   </tr>

   <tr>
       <td> 10/03/2018 </td>
       <td> 6 heures</td>
       <td> <%= image_tag 'https://clowntownforkidz.files.wordpress.com/2014/01/clown-charlie-chaplin1.jpg', width: 35, height: 35, class: "avatar-courte" %> Jean Jacques Michu</td>
       <td> - 12 € </td>
   </tr>


    <tr>
       <td> 26/03/2018 </td>
       <td> 6 heures </td>
       <td> <%= image_tag 'https://image.tmdb.org/t/p/original/1uwX5nQkqZx5Hus2IJW6gEACX7Z.jpg', width: 35, height: 35, class: "avatar-courte" %> Djamel Sour </td>
       <td> - 18 € </td>
    </tr>
</table>
<p> Prix mensuel de mon véhicule après locations Courte Durée: <span id="price-after"></span>€ par mois</p>
</div>


    </div>
  </div>

app/views/dashboards/profile.html.erb
<div class="body-wrap">
  <div class="container">
    <%= render 'subnav' %>

    <div class="dash">
      <div class="driver-profile">
        <%= cl_image_tag @driver_profile.photo, class: "avatar-large" %> &nbsp;
        <div class="driver-contact">
          <h2><%= @driver_profile.first_name %> <%= @driver_profile.last_name %></h2>
          <p class="driver-email"><i class="fas fa-envelope"></i> <%= @driver_profile.email %></p>
          <p class="driver-phone"><i class="fas fa-phone-square"></i> <%= @driver_profile.telephone_number %></p>
        </div>
        <%= link_to 'Modifier mon profil', profil_edit_path, class: 'btn-smap-secondary' %>
      </div>

      <hr>

      <div class="complementary-informations">
        <ul>
          <li>
            <p class="title">Adresse</p>
            <p class="value"><%= @driver_profile.address %> <%= @driver_profile.city %> <%= @driver_profile.zip_code %></p>
          </li>
          <li>
            <p class="title">Date de naissance</p>
            <p class="value"><%= @driver_profile.birthdate %></p>
          </li>
          <li>
            <p class="title">Permis de conduire</p>
            <p class="value">
              <% if @driver_profile.driving_license.blank? %>
                <%= link_to "Ajouter mon permis de conduire", profil_edit_path%>
              <% else %>
                <i class="fas fa-check"></i>
              <% end %>
            </p>
          </li>
          <li>
            <p class="title">Carte d'identité</p>
            <p class="value">
              <% if @driver_profile.identity_card.blank? %>
                <%= link_to "Ajouter ma carte d'identité", profil_edit_path %>
              <% else %>
                <i class="fas fa-check"></i>
              <% end %>
            </p>
          </li>
        </ul>
        <% if  @driver_profile.city? %>

        <%= image_tag("https://maps.googleapis.com/maps/api/staticmap?center=#{@driver_profile.city}&zoom=13&size=150x150&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284") %>
        <% end %>
      </div>

      <hr>

      <div class="car-informations">
        <div class="car-main-infos">
          <% if @car.blank? %>
            <%= link_to "Louez votre 1er véhicule", cars_path %>
          <% else %>
            <%= cl_image_tag @car.photo, width: 330, height: 165, class: "car-avatar" %>
            <div>
              <h4><%= @car.brand %>  <%= @car.model %></h4>
              <div class="rating">
                <% if @car.ratings.present? %>
                  <% 5.times do |i| %>
                    <%= icon('fas', 'star', class: "#{'smap-color' if @car.note > (i + 1)} ") %>
                  <% end %>
                <% else %>
                  Cette voiture n'a pas encore de notes
                <% end %>
              </div>
            </div>
          </div>
          <ul class="car-details">
            <li>
              <p class="icon">
                <i class="fas fa-users smap-color"></i>
              </p>
              <p class="value"><%= @car.seat %> Places</p>
            </li>
            <li>
              <p class="icon">
                <i class="tiny material-icons smap-color">local_gas_station</i>
              </p>
              <p class="value"><%= @car.energy %></p>
            </li>
            <li>
              <p class="icon">
                <i class="fas fa-cogs smap-color"></i>
              </p>
              <p class="value"><%= @car.transmission %></p>
            </li>
            <li>
              <p class="icon">
                <i class="fas fa-car smap-color"></i>
              </p>
              <p class="value"><%= @car.car_door %> Portes</p>
            </li>
            <li>
              <p class="icon">
                <i class="fas fa-suitcase smap-color"></i>
              </p>
              <p class="value"><%= @car.lugage %> Bagages</p>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="body-wrap">
  <div class="container">
    <%= render 'subnav' %>

    <div class="dash">
       <div class="conducteurs">
        <div class="flex" >
          <%= cl_image_tag @driver_profile.photo, class: "avatar-main" %>
          <div class="principal">
            <h6> <%= @driver_profile.first_name %>  <%= @driver_profile.last_name %> </h6>
            <p>(Conducteur principal)</p>
         </div>
       </div>

       <div class="credential">
         <div class="driving-license">
           <% if @driver_profile.driving_license.blank? %>
            <h4>Permis de conduire : <i class="fas fa-times"></i></h4>
           <%= link_to "Ajouter le permis de conduire", profil_edit_path%>
           <% else %>
           <h4>Permis de conduire : </h4>
            <i class="fas fa-check"></i>
           <% end %>
         </div>
         <div class="id-card">
           <% if @driver_profile.identity_card.blank? %>
            <h4>Permis de conduire : <i class="fas fa-times"></i></h4>
           <%= link_to "Ajouter la carte d'identité", profil_edit_path%>
           <% else %>
           <h4>Carte d'identité : </h4>
            <i class="fas fa-check"></i>
           <% end %>
         </div>
       </div>
      </div>
      <% @driver_profile.additional_drivers.each do |ad| %>
      <hr>
      <div class="conducteur-secondaire">
        <div class="flex" >
          <%= cl_image_tag ad.photo.url, class: "avatar-main" %> &nbsp;
          <div class="secondaire">
            <h4> <%= ad.first_name %> <%= ad.last_name %> <%= link_to icon('fas', 'pencil-alt'), edit_additional_driver_path(ad) %></h4>
            <p>(Conducteur secondaire) <%= link_to icon('fas', 'trash-alt'), additional_driver_path(ad), data: { confirm: "Are you sure?" }, method: :delete %>
            </p>
         </div>
       </div>
       <div class="credential">
         <div class="driving-license">
           <% if ad.driving_license.blank? %>
           <h4>Permis de conduire : <i class="fas fa-times"></i></h4>
           <%= link_to "Ajouter le permis de conduire", edit_additional_driver_path(ad)%>
           <% else %>
           <h4>Permis de conduire : </h4>
            <i class="fas fa-check"></i>
           <% end %>
         </div>
         <div class="id-card">
           <% if ad.identity_card.blank? %>
           <h4>Permis de conduire : <i class="fas fa-times"></i></h4>
           <%= link_to "Ajouter la carte d'identité", edit_additional_driver_path(ad)%>
           <% else %>
           <h4>Carte d'identité : </h4>
            <i class="fas fa-check"></i>
           <% end %>
         </div>
       </div>
     </div>
       <% end %>
    </div>
       <a href="<%= new_additional_driver_path %>" class="flex text-center add" >
        <div>
          <i class="fas fa-plus-circle smap-color ico"></i> <h5> Ajouter un conducteur secondaire</h5>
        </div></a>
  </div>
</div>

app/views/dashboards/slot.html.erb
<div class="body-wrap">
  <div class="container">
    <%= render 'subnav' %>

    <div class="dash">
      <p><%= link_to 'Ajouter une adresse', new_address_path, class: "btn-smap-secondary" %></p>
      <% if @driver_profile.addresses.present? %>
        <% if @driver_profile.addresses.count > 1 %>
          <h3>Toutes mes disponibilités</h3>
          <div id="general-calendar"></div>
          <h3>Mes adresses :</h3>
          <div class="panel-group" id="addresses-accordion">
            <% @driver_profile.addresses.each_with_index do |address, index| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <a role="button" data-toggle="collapse" data-parent="#addresses-accordion" href="#address<%= index + 1 %>">
                    <h4 class="panel-title">
                      <span class="address-name"><%= address.name %></span>
                      :
                      <%= address.address %>
                      <%= address.zip_code %>
                      <%= address.city %>
                    </a>
                  </h4>
                </div>
                <div id="address<%= index + 1 %>" class="panel-collapse collapse">
                  <div class="panel-body">
                    <ul>
                      <% address.slots.each do |slot| %>
                        <li class="slots" style="display: none">
                          <span class="slot-from-<%= index %>"><%= slot.from.strftime("%FT%T%:z") %></span>
                          //
                          <span class="slot-to-<%= index %>"><%= slot.to.strftime("%FT%T%:z") %></span>
                        <% end %>
                    </ul>
                    <div class="calendar"></div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <h3>Mes adresses :</h3>
          <div class="panel-group" id="addresses-accordion">
            <% @driver_profile.addresses.each_with_index do |address, index| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <a role="button" data-toggle="collapse" data-parent="#addresses-accordion" href="#address<%= index + 1 %>">
                    <h4 class="panel-title">
                      <span class="address-name"><%= address.name %></span>
                      :
                      <%= address.address %>
                      <%= address.zip_code %>
                      <%= address.city %>
                    </a>
                  </h4>
                </div>
                <div id="address<%= index + 1 %>" class="panel-collapse collapse in">
                  <div class="panel-body">
                    <ul>
                      <% address.slots.each do |slot| %>
                        <li class="slots" style="display: none">
                          <span class="slot-from-<%= index %>"><%= slot.from.strftime("%FT%T%:z") %></span>
                          //
                          <span class="slot-to-<%= index %>"><%= slot.to.strftime("%FT%T%:z") %></span>
                        <% end %>
                    </ul>
                    <div class="calendar"></div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>