config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :cars, only: [:index, :show]

  resources :additional_drivers, only: [:new, :edit, :update, :create, :destroy]

  resources :addresses, only: [:new, :edit, :update, :create, :destroy]

  resources :slots, only: [:new, :edit, :update, :create, :destroy]
  post 'dashboard/slot', to: 'slots_json#create', as: :dashboard_slot_json

  #Estimation et souscription

  get "/cars/:id/estimation", to: "cars#estimation", as: "estimation"
  get "/cars/:id/souscription", to: "cars#souscription", as: "souscription"

  #Dashboard routes
  get "/dashboard", to: "dashboards#show", as: :dashboard
  get "/dashboard/bill", to: "dashboards#bill", as: :dashboard_bill
  get "/dashboard/slot", to: "dashboards#slot", as: :dashboard_slot
  get "/profil", to: "dashboards#profile", as: :dashboard_profile

  #Profil routes
  get "/profil/edit", to: "driver_profiles#edit"
  patch "/profil", to: "driver_profiles#update"
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :slots, dependent: :destroy
  has_many :ratings

  include AlgoliaSearch

  algoliasearch do
    attribute :category, :brand, :model, :energy, :monthly_price, :seat, :lugage, :transmission, :car_door, :photo
    searchableAttributes ['category', 'brand', 'energy', 'monthly_price', 'seat', 'lugage', 'transmission', 'car_door', 'model']
    attributesForFaceting [:category, :brand, :energy, :monthly_price, :seat, :lugage, :transmission, :car_door]
    tags ['trusted']
  end

  def note
    ratings.sum(:rate) / ratings.count
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show, :estimation]

  def home
    @cars = Car.all
  end

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def estimation
    @car = Car.find(params[:id])
  end

  def souscription
    @car = Car.find(params[:id])
    @driver_profile = DriverProfile.find_by user: current_user
    @driver_profile.car = @car
    if @driver_profile.driving_license? && @driver_profile.identity_card?
      if @driver_profile.save
        redirect_to dashboard_path
      else
        render :estimation
      end
    else
      @driver_profile.save
      redirect_to profil_edit_path
      flash.alert = "Vous devez renseigner votre permis et CI."
    end
  end
end

app/views/cars/estimation.html.erb
<% content_for :meta_title, "Estimez votre tarif réduit pour #{@car.brand} #{@car.model} sur #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @car.description %>
<% content_for :meta_image, cl_image_path(@car.photo) %>

<div class="body-wrap">
  <div class="container">
    <h1 class="text-center" style="margin-bottom: 45px;" >Estimer ma facture mensuelle avec SMAP</h1>
    <div class="flex-estim">
      <div class="contrat">
        <h2><%= @car.brand %> <%= @car.model %>, <span id="category-estimation"><%= @car.category %></span></h2>
        <h3>Le prix du véhicule Smap est de <%= @car.monthly_price %>€ par mois. <br> Ce prix comprend :</h3>
        <ul>
          <li>Le carburant (30 000km sur 24mois)</li>
          <li>L'assurance</li>
          <li>L'entretien</li>
        </ul>
        <div class="car-card">
          <p>
              Lorsque je ne l'utilise pas, je rends ma voiture disponible à la sous-location sur le site Smap. Une partie de ces sous-locations viendront réduire ma facture mensuelle. <br>
              J'optimise donc simplement l'utilisation et le coût de mon véhicule!
          </p>
          <div class="infobull">
            <p>Au minimum, <strong>20% des disponibiltés</strong> renseignées sur le mois seront sous-louées. L'estimation prend en compte ce paramètre.</p>
            <%= image_tag "https://a0.muscache.com/airbnb/static/page3/icon-uc-light-bulb-b34f4ddc543809b3144949c9e8cfcc8d.gif"%>
          </div>
        </div>
      </div>
      <div class="estimer text-center">
        <h4>Du lundi au vendredi ma voiture sera disponible :</h4><h2><span id="sval" >60</span> heures</h2>
        <br>
        <input id="semaine" class="slider" type="range" min="0" max="120" step="1" />
        <br>
        <h4>Le week-end, elle sera disponible :</h4> <h2><span id="wval">24</span> heures </h2>
        <br>
        <input id="weekend" class="slider" type="range" min="0" max="48" step="1" />
        <br>
        <div class="result-estim">
          <div>
            <div class="tarif">
              <h5><strong><span id="tarif"><%= @car.monthly_price %></span> € / mois</strong></h5>
            </div>
            <div class="reduction">
              <strong><h2>-<span id="reduc"></span>€<h2></i></strong>
            </div>
          </div>
          <div class="estimation-result">
            <h5>Tarif estimé</h5>
            <h2><strong><span id="estimation"><%= @car.monthly_price %></span>€ / mois</strong></h2>
          </div>
        </div>
        <%= link_to "Souscrire à SMAP ! ", souscription_path(@car), class: "btn-smap" %>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="flex-container">
  <div class="filter-container">
    <div id="clear-all"></div>
    <div id="monthly_price"></div>
    <br>
    <div id="energy"></div>
    <br>
    <div id="transmission"></div>
    <br>
    <div id="category"></div>
    <br>
    <div id="brand"></div>
    <br>
    <div id="portes"></div>
    <br>
    <div id="places"></div>
  </div>

  <div class="cars-container flex-grow">
    <div class="row">
      <div class="col-xs-12">
        <div id="search-box" class="searchbar">
          <i class="fab fa-algolia algoli-logo"></i>
        </div>
        <div class="row">
          <div id="hits"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<% content_for :meta_title, "#{@car.brand} #{@car.model} est sur #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @car.description %>
<% content_for :meta_image, cl_image_path(@car.photo) %>

<div class="body-wrap">
  <div class="container">
    <div class="dash">
      <div class="car-dash">
        <div>
          <h1 style="margin-top: 0;"><%= @car.brand %> <%= @car.model %>, <em style="font-size: 17px;"> <%= @car.category %></em></h1>
          <%= cl_image_tag @car.photo, width: 330, height: 165, class: "car-avatar" %>
        </div>
        <div class="icon-list">
          <div class="icon-card">
            <h4 class="icons-li"><i class="fas fa-users smap-color"></i> &nbsp; <%= @car.seat %> Places</h4>
            <h4 class="icons-li"><i class="tiny material-icons smap-color" style="font-size: 30px" >local_gas_station</i> &nbsp; <%= @car.energy %></h4>
          </div>
          <div class="icon-card">
            <h4 class="icons-li"><i class="fas fa-cogs smap-color"></i> &nbsp; <%= @car.transmission %></h4>
            <h4 class="icons-li"><i class="fas fa-car smap-color"></i> &nbsp; <%= @car.car_door %> Portes</h4>
          </div>
          <div class="icon-card">
            <h4 class="icons-li"><i class="fas fa-suitcase smap-color"></i> &nbsp; <%= @car.lugage %> Bagages</h4>
          </div>
        </div>
      </div>
      <div class="info-container">
        <div class="description">
          <p><%= @car.description %></p>
        </div>
      </div>
    </div>
    <div class="flex-show">
      <div class="contract">
        <div class="contract-text">
          <h2>Le contrat SMAP, engagement 24 mois :</h2>
          <ul>
            <li>Le carburant (30 000km sur 24mois)</li>
            <li>L'entretien</li>
            <li>L'assurance</li>
          </ul>
          <%= link_to "Estimer ma facture", estimation_path(@car), class: "btn-smap" %>
        </div>
       </div>
      <div class="contract-container">
        <p><strong>Concessionnaire :</strong> <span id="concessionnaire_name"><%= @car.concessionnaire_name %></span><span id="concessionnaire_address"><%= @car.concessionnaire_address %></span></p>
        <div id="map" class="car-picture"></div>
      </div>
    </div>
  </div>
</div>